from llm_sdk import Small_LLM_Model  # type: ignore[attr-defined]
from .schema import FunctionSpec, FunctionCall
import json
import re
import numpy as np


def load_vocab(model: Small_LLM_Model) -> dict[int, str]:
    """Load the tokenizer vocabulary as a {token_id: token_str} mapping."""
    path = model.get_path_to_tokenizer_file()
    with open(path, encoding="utf-8") as file:
        tok = json.load(file)
    return {v: k for k, v in tok["model"]["vocab"].items()}


def generate_constrained(
    model: Small_LLM_Model,
    input_ids: list[int],
    valid_token_ids: list[int],
    verbose: bool = False,
    vocab: dict[int, str] | None = None,
) -> int:
    """Return the highest-logit token ID among valid_token_ids.

    All other token positions are masked to -inf before argmax, ensuring the
    model can only emit tokens that keep the output on a valid path.
    """
    logits = model.get_logits_from_input_ids(input_ids)
    mask = np.full(len(logits), -np.inf)
    for token_id in valid_token_ids:
        mask[token_id] = logits[token_id]
    chosen = int(np.argmax(mask))
    if verbose:
        chosen_str = vocab[chosen] if vocab is not None else str(chosen)
        print(
            f"    candidates: {len(valid_token_ids)}"
            f"  chosen: {chosen_str!r} (id {chosen})"
        )
    return chosen


def select_function(
    model: Small_LLM_Model,
    vocab: dict[int, str],
    user_prompt: str,
    functions: list[FunctionSpec],
    verbose: bool = False,
    prefix_ids: list[int] | None = None,
) -> FunctionSpec:
    """Pick the best-matching function for a natural language prompt.

    Uses constrained decoding to generate the function name token by token.
    At each step, only tokens that extend the current prefix toward a valid
    function name are allowed, guaranteeing a valid selection.
    """
    prompt = _build_prompt(user_prompt, functions)
    input_ids = model.encode(prompt).tolist()[0]
    if prefix_ids is None:
        prefix_ids = model.encode('{"name":"').tolist()[0]
    input_ids = input_ids + prefix_ids

    fn_names = [f.name for f in functions]
    generated_prefix = ""

    if verbose:
        print("  [function selection]")
        print("    prefix: ", end="", flush=True)

    while True:
        valid = _get_valid_tokens(vocab, fn_names, generated_prefix)
        if not valid:
            raise ValueError(
                f"Constrained decoding stuck: no valid tokens for prefix "
                f"{generated_prefix!r}. Available functions: {fn_names}"
            )
        next_token = generate_constrained(
            model, input_ids, valid, verbose, vocab
        )
        token_str = vocab[next_token]
        generated_prefix += token_str
        input_ids.append(next_token)

        if generated_prefix.endswith('"'):
            generated_prefix = generated_prefix[:-1]
            break

        if verbose:
            print(token_str, end="", flush=True)

    if verbose:
        print(f"\n    selected: {generated_prefix}")

    return next(f for f in functions if f.name == generated_prefix)


def extract_arguments(
    model: Small_LLM_Model,
    vocab: dict[int, str],
    user_prompt: str,
    function: FunctionSpec,
    verbose: bool = False,
) -> dict[str, float | str]:
    """Extract parameter values for the given function from the user prompt.

    Numeric parameters are read directly from the prompt using regex.
    String parameters are generated by the model via greedy decoding.
    """
    result: dict[str, float | str] = {}
    numbers = re.findall(r'-?\d+(?:\.\d+)?', user_prompt)
    number_idx = 0

    if verbose:
        print("  [argument extraction]")

    for param_name, param_spec in function.parameters.items():
        if param_spec.type == "number" or param_spec.type == "integer":
            if number_idx >= len(numbers):
                raise ValueError(
                    f"Could not extract numeric argument '{param_name}' for function "
                    f"'{function.name}': no numbers found in prompt {user_prompt!r}"
                )
            if param_spec.type == "number":
                value = float(numbers[number_idx])
            else:
                value = int(numbers[number_idx])
            result[param_name] = value
            number_idx += 1
            if verbose:
                print(f"    {param_name} = {value}  (from prompt)")
        elif param_spec.type == "string":
            value_str = _extract_string(
                model, vocab, user_prompt, function.name, param_name, verbose
            )
            result[param_name] = value_str
    return result


def generate(
    model: Small_LLM_Model,
    vocab: dict[int, str],
    prompt: str,
    functions: list[FunctionSpec],
    verbose: bool = False,
    prefix_ids: list[int] | None = None,
) -> FunctionCall:
    """Translate a natural language prompt into a structured FunctionCall."""
    function = select_function(
        model, vocab, prompt, functions, verbose, prefix_ids
    )
    parameters = extract_arguments(model, vocab, prompt, function, verbose)
    return FunctionCall(
        prompt=prompt,
        name=function.name,
        parameters=parameters)


# --- helpers -----------------------------------------------------------------

def _build_prompt(user_prompt: str, functions: list[FunctionSpec]) -> str:
    """Build the instruction prompt listing all available functions."""
    lines = []
    for i, f in enumerate(functions, 1):
        params = ", ".join(
            f"{name}: {spec.type}"
            for name, spec in f.parameters.items()
        )
        lines.append(f"{i}. {f.name} | {f.description} | params: {params}")

    return (
        "You are a function-calling machine.\n"
        "Do not answer the user directly.\n"
        "Choose one of the following functions:\n"
        + "\n".join(lines)
        + f'\n\nUser prompt: "{user_prompt}"\n'
        'Function: "'
    )


def _get_valid_tokens(
    vocab: dict[int, str],
    fn_names: list[str],
    generated_prefix: str,
) -> list[int]:
    """Return token IDs that extend the prefix toward a valid function name."""
    targets = [f'{name}"' for name in fn_names]
    return [
        token_id for token_id, token_str in vocab.items()
        if any(t.startswith(generated_prefix + token_str) for t in targets)
    ]


def _extract_string(
    model: Small_LLM_Model,
    vocab: dict[int, str],
    user_prompt: str,
    fn_name: str,
    param_name: str,
    verbose: bool = False,
) -> str:
    """Generate a string argument value using greedy decoding.

    The prompt format is chosen based on the parameter name to steer the model:
    - regex/pattern: code-completion format to produce valid regex syntax.
    - replacement: extracted from the prompt if uppercase, otherwise generated.
    - other strings: a short instruction prompt followed by completion.

    Generation stops as soon as the model emits a token containing a quote.
    """
    prompt = user_prompt

    if param_name in ("regex", "pattern"):
        # Code-completion format steers the model toward valid regex syntax.
        prompt = f"# {user_prompt}\n{param_name} = \""
    elif param_name == "replacement":
        match = re.search(r'\bwith\s+([A-Z][A-Z]+)\b', user_prompt)
        if match:
            extracted = match.group(1)
            if verbose:
                print(f"    {param_name} = {extracted!r}  (from prompt)")
            return extracted
        prompt = (
            f'User said: "{user_prompt}"\n'
            f'What exact string should replace each match? {param_name} = "'
        )
    elif param_name == "path":
        match = re.search(r'([A-Za-z]:\\[\w\\./:-]+|/[\w./:-]+)', user_prompt)
        if match:
            extracted = match.group(1)
            if verbose:
                print(f"    {param_name} = {extracted!r}  (from prompt)")
            return extracted
        prompt = (
            f'User said: "{user_prompt}"\n'
            f'What path is he referring to in the prompt? {param_name} = "'
        )
    elif param_name == "template":
        match = re.search(r'[Ff]ormat\s+template:\s*(.+)', user_prompt)
        if match:
            extracted = match.group(1)
            if verbose:
                print(f"    {param_name} = {extracted!r}  (from prompt)")
            return extracted
    else:
        prompt = (
            f'User said: "{user_prompt}"\n'
            f'Function {fn_name} needs string argument "{param_name}".\n'
            f'{param_name} = "'
        )

    # greedy decoding: pick argmax token by token until a quote appears ---

    input_ids = model.encode(prompt).tolist()[0]
    generated_ids = []
    token_str = ""

    if verbose:
        print(f"    {param_name} = \"", end="", flush=True)

    for _ in range(80):
        logits = model.get_logits_from_input_ids(input_ids)
        next_token = int(np.argmax(logits))
        token_str = vocab[next_token]
        if '"' in token_str:
            part = token_str[:token_str.index('"')]
            if part:
                if verbose:
                    print(part, end="", flush=True)
                result_suffix = part
            else:
                result_suffix = ""
            break
        generated_ids.append(next_token)
        input_ids.append(next_token)
        if verbose:
            print(token_str, end="", flush=True)
    else:
        result_suffix = ""

    if verbose:
        print('"')

    result: str = model.decode(generated_ids) + result_suffix

    # The model sometimes repeats the same character (e.g. "**" instead of "*")
    if len(result) > 1 and len(set(result)) == 1:
        result = result[0]

    # The model sometimes opens a group "([0-9]+" without closing it
    if result.startswith("(") and result.count("(") > result.count(")"):
        result = result[1:]

    return result
